name: Build nxtx package and publish

on:
  pull_request:
    branches: release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: '10.x'
      -
        name: Install dependencies
        run: npm install --ignore-scripts
      -
        name: Build unminified
        run: npm run build:dev
      -
        name: Build minified
        run: npm run build
      -
        name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
